import = [ "~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml", "~/.local/share/defaults/alacritty.toml" ]

[font]
size = 12

[env]
TERM = "xterm-256color"

[window]
padding.x = 16
padding.y = 14
decorations = "none"
opacity = 0.97
