export PATH="$HOME/.ndenv/bin:$PATH"
export PATH="$PATH:$HOME/.dotfiles/bin"

source ~/.dotfiles/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle tmux
antigen bundle npm
antigen bundle git
antigen bundle command-not-found
antigen bundle Tarrasch/zsh-autoenv

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme robbyrussell
# antigen theme agnoster

# Tell antigen that you're done.
antigen apply

eval "$(ndenv init -)"
eval "$(rbenv init -)"
if which jenv > /dev/null; then eval "$(jenv init -)"; fi

alias ctags="`brew --prefix`/bin/ctags"

# How much time to wait for additional characters in sequence
KEYTIMEOUT=1

# added by travis gem
[ -f /Users/enric/.travis/travis.sh ] && source /Users/enric/.travis/travis.sh

# execute first local npm bin
function npm-do { (PATH=$(npm bin):$PATH; eval $@;) }

# export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-7.jdk/Contents/Home
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
export M2_HOME=/usr/local/Cellar/maven@3.0/3.0.5/libexec
export M2=$M2_HOME/bin
export PATH=$PATH:$M2_HOME/bin
export MAVEN_OPTS="-Xmx3000m -XX:PermSize=1024m -XX:MaxPermSize=1024m"
