[general]
import = [
  "~/.config/alacritty/themes/themes/autumn.toml"
]

[font]
size = 11.0

[terminal.shell]
program = "/usr/bin/tmux" # Ubuntu
# program = "/opt/homebrew/bin/tmux" # MAC OS

[env]
TERM="xterm-256color"
